# Generated by Django 3.1.2 on 2021-12-16 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211216_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')], default=None, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
