# Generated by Django 3.1.2 on 2021-12-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211216_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')], default=1, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
