# Generated by Django 3.1 on 2021-12-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211217_1119'),
        ('orders', '0004_auto_20211217_1043'),
    ]

    operations = [
    ]
