# Generated by Django 3.1.2 on 2021-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211217_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MARKET'), (2, 'LIMIT'), (3, 'STOPMARKET'), (4, 'STOPLIMIT')], default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')], default=1, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
