# Generated by Django 3.1.2 on 2021-12-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211217_1043'),
        ('orders', '0004_auto_20211217_1442'),
    ]

    operations = [
    ]
