# Generated by Django 3.1.2 on 2021-12-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20211217_1531'),
        ('orders', '0005_auto_20211217_1527'),
    ]

    operations = [
    ]
