# Generated by Django 3.1.2 on 2021-12-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20211218_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
