# Generated by Django 3.1.2 on 2021-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'EXECUTED'), (3, 'CANCELLED'), (4, 'RUNNING')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MARKET'), (2, 'LIMIT'), (3, 'STOPMARKET'), (4, 'STOPLIMIT')], default=1, verbose_name='Type'),
        ),
    ]
