# Generated by Django 3.1.2 on 2021-12-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211218_2031'),
        ('orders', '0006_merge_20211218_1457'),
    ]

    operations = [
    ]
