# Generated by Django 3.1 on 2021-12-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_merge_20211218_1444'),
        ('orders', '0009_merge_20211218_2350'),
    ]

    operations = [
    ]
