# Generated by Django 3.1.2 on 2021-12-19 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20211219_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
