# Generated by Django 3.1.2 on 2021-12-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_executed_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-placed_time']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='placed_time',
        ),
    ]
