# Generated by Django 3.1.2 on 2021-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
