# Generated by Django 3.1.2 on 2021-12-25 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20211219_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('message', models.CharField(default='', max_length=100, verbose_name='Account Message')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'SUCCESS'), (2, 'CANCELLED')], default=1, verbose_name='Account Status')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account Book')),
            ],
        ),
    ]
