# Generated by Django 3.1 on 2021-12-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211219_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.CharField(default='', max_length=50),
        ),
    ]
