# Generated by Django 3.1.2 on 2021-12-25 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_accountbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbook',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CREDIT'), (2, 'DEBIT')], default=1, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 11, 22, 0, 604703, tzinfo=utc)),
        ),
    ]
