# Generated by Django 3.1 on 2021-12-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_referral'),
        ('dashboard', '0008_auto_20211225_1652'),
    ]

    operations = [
    ]
