# Generated by Django 3.1.2 on 2021-12-25 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211225_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 19, 29, 49, 47212, tzinfo=utc)),
        ),
    ]
