# Generated by Django 3.1.2 on 2021-12-26 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211226_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
