# Generated by Django 3.1 on 2021-12-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211227_0229'),
        ('dashboard', '0009_merge_20211227_0033'),
    ]

    operations = [
    ]
