# Generated by Django 3.1 on 2021-10-11 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_forgotpassword_datastamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='datastamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
