# Generated by Django 3.1 on 2021-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('symbol', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Coin',
            },
        ),
    ]
