# Generated by Django 3.1.2 on 2021-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_coin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
