# Generated by Django 3.1.2 on 2021-12-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_auto_20211215_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['-symbol']},
        ),
    ]
